feat: reset and removing parameter from tick
EdenComp/Arcade-Common pull request #5
Opened 2023-03-27 09:34 UTC by EdenComp

2023-03-27 13:27 UTC, Tomi-Tom approved these changes
Ya ya, da da

2023-03-27 13:28 UTC, Steci approved these changes

2023-03-28 09:25 UTC, Croos3r requested changes

2023-03-28 09:25 UTC, Croos3r commented on include/common/game/IGameModule.hpp
> +            virtual void reset() = 0;
da remove fast asap connard @EdenComp

2023-03-28 11:45 UTC, EdenComp commented
49.3

2023-03-28 11:45 UTC, merged